namespace Enums
{
    public enum MenuButtonType
    {
        TodayButton,
        GameButton,
        TestButton,
        SettingsButton,
        NotificationsButton,
        SettingsBack,
        NotificationBack,
        BallSortGame,
        CardMatchGame,
        BallSortCoverPage,
        CardMatchCoverPage,
        IqTest,
        AnxietyTest,
        PersonalityTest,
        TrashSortGame,
        TrashSortCoverPage,
        SociabilityTest,
        BigFiveTest,
        MathFundamentalGame,
        MathFundamentalCoverPage,
        AggressionTest,
        CapitalTest,
        EmotionalTest,
        OptimistTest,
        SocialIntelligence
    }
}